language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk8
env:
  - NODE_VERSION=12.6.0

install:
  - nvm install $NODE_VERSION

script:
  - nvm use $NODE_VERSION
  - dir
  - cd typescryptimplementation
  - npm install grunt-cli --save-dev
  - npm install grunt@0.4.5 --save-dev
  - npm install grunt-template-jasmine-istanbul@0.2.5 --save-dev
  - npm install grunt-template-jasmine-requirejs@0.1.7 --save-dev
  - npm install grunt-contrib-jasmine@0.5.2 --save-dev
  - npm install grunt-typescript --save-dev
  - npm install grunt-contrib-clean --save-dev
  - npm install grunt-contrib-uglify --save-dev
  - npm install grunt-contrib-yuidoc --save-dev
  - dir
  - npm install
  - dir
  - cd ..
  - mvn test -B
